export const paths = {
    languageSelection: "LanguageSelection",
    login: "Login",
    registerSelection: "RegisterSelection",
    register: "Register",
    registerWorkshop: "RegisterWorkshop",
    adminDashboard: "AdminDashboard",
    dashboard: "Dashboard",
    profile: "Profile",
    workshops: "Workshops",
    cuts: "Cuts",
    batches: "Batches",
    batchOffer: "BatchOffer",
    workshopStatus: "WorkshopStatus",
    finishedProduction: "FinishedProduction",
    receivePieces: "ReceivePieces",
    payments: "Payments",
    financialHistory: "FinancialHistory",
    generalHistory: "GeneralHistory",
    metrics: "Metrics",
    plans: "Plans",
    basicPlan: "BasicPlan",
    premiumPlan: "PremiumPlan",
    enterprisePlan: "EnterprisePlan",
    planCheckout: "PlanCheckout",
} as const;

export type ScreenName = (typeof paths)[keyof typeof paths];

export const publicRoutes: ScreenName[] = [
    paths.languageSelection,
    paths.login,
    paths.registerSelection,
    paths.register,
    paths.registerWorkshop,
];

export const protectedRoutes: ScreenName[] = [
    paths.adminDashboard,
    paths.dashboard,
    paths.profile,
    paths.workshops,
    paths.cuts,
    paths.batches,
    paths.batchOffer,
    paths.workshopStatus,
    paths.finishedProduction,
    paths.receivePieces,
    paths.payments,
    paths.financialHistory,
    paths.generalHistory,
    paths.metrics,
    paths.plans,
    paths.basicPlan,
    paths.premiumPlan,
    paths.enterprisePlan,
    paths.planCheckout,
];